// Complete migration data from existing AniPins website
// All 296 artworks with metadata

export const MIGRATION_BASE = 'https://anipins-three.vercel.app';

export interface MigratedArtwork {
  title: string;
  character: string;
  anime: string;
  thumbnailHash: string;
  orientation: string;
  category: string;
}

// All artwork data from live site inspection
export const ALL_ARTWORKS: MigratedArtwork[] = [
  { title: 'Kenny Ackerman', character: 'Kenny Ackerman', anime: 'Attack on Titan', thumbnailHash: 'c0f887ec2e32ccd0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Himiko Toga', character: 'Himiko Toga', anime: 'My Hero Academia', thumbnailHash: '5b8b889d3d51a77f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Pieck Finger', character: 'Pieck Finger', anime: 'Attack on Titan', thumbnailHash: '42b35b7aee9a202e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Dabi', character: 'Dabi', anime: 'My Hero Academia', thumbnailHash: 'd2a245fdc00df17d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tomura Shigaraki', character: 'Tomura Shigaraki', anime: 'My Hero Academia', thumbnailHash: 'a23045a34031d875', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Falco Grice', character: 'Falco Grice', anime: 'Attack on Titan', thumbnailHash: '008661fcf8c24681', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Gabi Braun', character: 'Gabi Braun', anime: 'Attack on Titan', thumbnailHash: '19afd8c301e4bae3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Endeavor', character: 'Endeavor', anime: 'My Hero Academia', thumbnailHash: '18b974b978c9d1fe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Zeke Yeager', character: 'Zeke Yeager', anime: 'Attack on Titan', thumbnailHash: 'd9509edc0f96a1c3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jogo', character: 'Jogo', anime: 'Jujutsu Kaisen', thumbnailHash: '76b5de96464392cc', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hawks', character: 'Hawks', anime: 'My Hero Academia', thumbnailHash: '0271c4f18cf23ee1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shota Aizawa', character: 'Shota Aizawa', anime: 'My Hero Academia', thumbnailHash: '6561cf1f06f7d99c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mahito', character: 'Mahito', anime: 'Jujutsu Kaisen', thumbnailHash: '8b781bb3ec8b5cbe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Annie Leonhart', character: 'Annie Leonhart', anime: 'Attack on Titan', thumbnailHash: 'd8195c9d25e02d1b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mina Ashido', character: 'Mina Ashido', anime: 'My Hero Academia', thumbnailHash: 'b2064cf3781c61e1', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Choso', character: 'Choso', anime: 'Jujutsu Kaisen', thumbnailHash: 'bd74ddd979f1b647', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Bertholdt Hoover', character: 'Bertholdt Hoover', anime: 'Attack on Titan', thumbnailHash: 'cb2bf04adcfa6840', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Reiner Braun', character: 'Reiner Braun', anime: 'Attack on Titan', thumbnailHash: '4469031dc42388f5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Fumikage Tokoyami', character: 'Fumikage Tokoyami', anime: 'My Hero Academia', thumbnailHash: 'ab96cbbe744fa874', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Sasha Blouse', character: 'Sasha Blouse', anime: 'Attack on Titan', thumbnailHash: '873dcc5ee62a5474', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Noble Lady', character: 'Noble Lady', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f164eb988b6e94ca', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Satoru Gojo 1', character: 'Satoru Gojo', anime: 'Jujutsu Kaisen', thumbnailHash: '3b03f60db649a61a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Albedo 1', character: 'Albedo', anime: 'Overlord', thumbnailHash: '84e8d288dccb7081', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Alya 1', character: 'Alya', anime: 'Alya Sometimes Hides Her Feelings', thumbnailHash: '74ad6b95452733e0', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Benimaru 1', character: 'Benimaru', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'ae5f0e293fff2bfc', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nacht Faust 1', character: 'Nacht Faust', anime: 'Black Clover', thumbnailHash: 'fbdccb28ecd90824', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Obito Uchiha 1', character: 'Obito Uchiha', anime: 'Naruto', thumbnailHash: '89397be8600cf38d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rimuru 1', character: 'Rimuru', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'f56eb2e3f12c334b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shinobu Kocho 1', character: 'Shinobu Kocho', anime: 'Demon Slayer', thumbnailHash: 'a7684990a336574b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Byakuya Kuchiki 1', character: 'Byakuya Kuchiki', anime: 'Bleach', thumbnailHash: 'a5afaafc2b2a9652', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Eren Yeager 1', character: 'Eren Yeager', anime: 'Attack on Titan', thumbnailHash: 'd1683ebe1303a20a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Frieren 1', character: 'Frieren', anime: 'Frieren Beyond Journey\'s End', thumbnailHash: '6703825bef7d7693', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ichigo Kurosaki 1', character: 'Ichigo Kurosaki', anime: 'Bleach', thumbnailHash: 'a5859dbe2d5dd730', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Julius Novachrono 1', character: 'Julius Novachrono', anime: 'Black Clover', thumbnailHash: 'de7788aa36fdae9b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Luck Voltia 1', character: 'Luck Voltia', anime: 'Black Clover', thumbnailHash: '8ebe2efe62125899', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Marin Kitagawa 1', character: 'Marin Kitagawa', anime: 'My Dress Up Darling', thumbnailHash: '2cd6ce0298dee9d3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mereleona 1', character: 'Mereleona', anime: 'Black Clover', thumbnailHash: '6ae80f7b9b5d2959', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mitsuri Kanroji 1', character: 'Mitsuri Kanroji', anime: 'Demon Slayer', thumbnailHash: 'c74efcafb5a1c873', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Naruto Uzumaki 1', character: 'Naruto Uzumaki', anime: 'Naruto', thumbnailHash: '6449adc1b938675a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Noelle Silva 1', character: 'Noelle Silva', anime: 'Black Clover', thumbnailHash: '9662e1fb56c5ab08', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nozel Silva 1', character: 'Nozel Silva', anime: 'Black Clover', thumbnailHash: '58fe8d69a2621421', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rias Gremory 1', character: 'Rias Gremory', anime: 'High School DxD', thumbnailHash: 'cf572ce03e26830a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Rimuru Tempest 1', character: 'Rimuru Tempest', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'dde3977604881403', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rukia Kuchiki 1', character: 'Rukia Kuchiki', anime: 'Bleach', thumbnailHash: 'c725aa080bfb2724', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shion 1', character: 'Shion', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: '566a22da8f29a222', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shuna 1', character: 'Shuna', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'cdb3348116ea4eee', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sosuke Aizen 1', character: 'Sosuke Aizen', anime: 'Bleach', thumbnailHash: 'b8689d43cf290820', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Souei 1', character: 'Souei', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'e9149d63486a01a7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Vanessa Enoteca 1', character: 'Vanessa Enoteca', anime: 'Black Clover', thumbnailHash: '5c22dd5f2a383100', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yachiru Kusajishi 1', character: 'Yachiru Kusajishi', anime: 'Bleach', thumbnailHash: '58865a5f162fba6c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yami Sukehiro 1', character: 'Yami Sukehiro', anime: 'Black Clover', thumbnailHash: '281910fa6c26a9c8', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yasutora Sado 1', character: 'Yasutora Sado', anime: 'Bleach', thumbnailHash: '4af093e4978ae932', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yuji Itadori 1', character: 'Yuji Itadori', anime: 'Jujutsu Kaisen', thumbnailHash: '289c69c8b2c243e3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yuno 1', character: 'Yuno', anime: 'Black Clover', thumbnailHash: 'ad2ad8ed2e097ca4', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Elinalise 1', character: 'Elinalise', anime: 'Jobless Reincarnation', thumbnailHash: 'a577b596b3645007', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Airi Sakura', character: 'Airi Sakura', anime: 'Classroom of the Elite', thumbnailHash: '4b9a7e511d990286', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Aki Hayakawa', character: 'Aki Hayakawa', anime: 'Chainsaw Man', thumbnailHash: '1aed3e5ce407f176', orientation: 'portrait', category: 'Male Characters' },
  { title: 'All Might', character: 'All Might', anime: 'My Hero Academia', thumbnailHash: 'c3bb4d6879a17f16', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Angel Devil', character: 'Angel Devil', anime: 'Chainsaw Man', thumbnailHash: '822415571da68141', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Anosh Voldigoad', character: 'Anosh Voldigoad', anime: 'The Misfit of Demon Academy', thumbnailHash: 'c19c2ec984262792', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Anya Forger', character: 'Anya Forger', anime: 'Spy x Family', thumbnailHash: 'f952d6efd6c0f2c9', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Aoi Todo', character: 'Aoi Todo', anime: 'Jujutsu Kaisen', thumbnailHash: '15488bc1d5e38d78', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Arataki Itto', character: 'Arataki Itto', anime: 'Genshin Impact', thumbnailHash: '32d23bf945818800', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Arisu Sakayanagi', character: 'Arisu Sakayanagi', anime: 'Classroom of the Elite', thumbnailHash: 'cf37f7164102ce3b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Armin Alert', character: 'Armin Alert', anime: 'Attack on Titan', thumbnailHash: '5959226fadf3ca00', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Asa Mitaka', character: 'Asa Mitaka', anime: 'Chainsaw Man', thumbnailHash: '43b412ca657ac66a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Askeladd', character: 'Askeladd', anime: 'Vinland Saga', thumbnailHash: 'd46fdac04c21d3c6', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Asta', character: 'Asta', anime: 'Black Clover', thumbnailHash: '89647794db2acd9a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Baek Yoonho', character: 'Baek Yoonho', anime: 'Solo Leveling', thumbnailHash: 'bc5fe4a088983909', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Becky Blackbell', character: 'Becky Blackbell', anime: 'Spy x Family', thumbnailHash: 'e3291d3a0bdce8d6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Bennett', character: 'Bennett', anime: 'Genshin Impact', thumbnailHash: '2c95482b305f6f11', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Beru', character: 'Beru', anime: 'Solo Leveling', thumbnailHash: 'dc0627d8a49ea5d8', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Bjorn', character: 'Bjorn', anime: 'Vinland Saga', thumbnailHash: '56a3db33c953aff7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Canute', character: 'Canute', anime: 'Vinland Saga', thumbnailHash: '3cb5a9086d9cb1b5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Cha Hae In', character: 'Cha Hae In', anime: 'Solo Leveling', thumbnailHash: '90dd408fbbc13e2b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Choi Jong In', character: 'Choi Jong In', anime: 'Solo Leveling', thumbnailHash: 'd15a027469c64e59', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Classmate', character: 'Classmate', anime: 'The Daily Life of the Immortal King', thumbnailHash: 'de1e0aebbdfa8235', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Connie Springer', character: 'Connie Springer', anime: 'Attack on Titan', thumbnailHash: 'c8560ffcc3accde0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Cyno', character: 'Cyno', anime: 'Genshin Impact', thumbnailHash: '53c3b1e9d572e394', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Damian Desmond', character: 'Damian Desmond', anime: 'Spy x Family', thumbnailHash: '592951eaea923b4c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Denji', character: 'Denji', anime: 'Chainsaw Man', thumbnailHash: 'a5607d36536875f5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Denki Kaminari', character: 'Denki Kaminari', anime: 'My Hero Academia', thumbnailHash: 'b56f8e45ffe3b909', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Eijiro Kirishima', character: 'Eijiro Kirishima', anime: 'My Hero Academia', thumbnailHash: '5ce3d33ad342dbd9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Einar', character: 'Einar', anime: 'Vinland Saga', thumbnailHash: 'da32bc7d2c83229c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Erdomaid Dittijohn', character: 'Erdomaid Dittijohn', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f8c18e6587bac566', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Erwin Smith', character: 'Erwin Smith', anime: 'Attack on Titan', thumbnailHash: '9b320f57492a3432', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Eula', character: 'Eula', anime: 'Genshin Impact', thumbnailHash: '176d446f029dd428', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Finral Roulacase', character: 'Finral Roulacase', anime: 'Black Clover', thumbnailHash: '0f99ecc5f6411a96', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Fiona Frost', character: 'Fiona Frost', anime: 'Spy x Family', thumbnailHash: 'fb70504ec674c1ee', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Fischl', character: 'Fischl', anime: 'Genshin Impact', thumbnailHash: '165eed2b293100b0', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Floki', character: 'Floki', anime: 'Vinland Saga', thumbnailHash: '3c66f6d69c1cd89d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Franky Franklin', character: 'Franky Franklin', anime: 'Spy x Family', thumbnailHash: '512534e883e9d246', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Furina', character: 'Furina', anime: 'Genshin Impact', thumbnailHash: '861ee658cd6ae69a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Gaara', character: 'Gaara', anime: 'Naruto', thumbnailHash: 'e073d5be94f06e01', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Ganyu', character: 'Ganyu', anime: 'Genshin Impact', thumbnailHash: '98cb70fd735fd14f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Genryusai Shingekuni', character: 'Genryusai Shingekuni', anime: 'Bleach', thumbnailHash: '2d3f906709e35389', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Giyu Tomioka', character: 'Giyu Tomioka', anime: 'Demon Slayer', thumbnailHash: 'be1abe172e95a80c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hange Zoe', character: 'Hange Zoe', anime: 'Attack on Titan', thumbnailHash: 'a87793a4a10ef69e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Himeno', character: 'Himeno', anime: 'Chainsaw Man', thumbnailHash: '2e17b56d88a3e320', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Hinata Hyuga', character: 'Hinata Hyuga', anime: 'Naruto', thumbnailHash: 'a455f39365192746', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Historia Reiss', character: 'Historia Reiss', anime: 'Attack on Titan', thumbnailHash: '8b01f7e26bc70468', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Holy Knight', character: 'Holy Knight', anime: 'The Misfit of Demon Academy', thumbnailHash: '040bba4e92e3cdc3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Hotaru', character: 'Hotaru', anime: 'Genshin Impact', thumbnailHash: '260f8532c346f827', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Hybrid Student', character: 'Hybrid Student', anime: 'The Misfit of Demon Academy', thumbnailHash: '1762c3777a0deae9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Igris', character: 'Igris', anime: 'Solo Leveling', thumbnailHash: '7d94fc8e99daa0d0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Immortal King', character: 'Immortal King', anime: 'The Daily Life of the Immortal King', thumbnailHash: '2917eb2cf8324771', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Inosuke Hashibira', character: 'Inosuke Hashibira', anime: 'Demon Slayer', thumbnailHash: '17d459204f46461d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Itachi Uchiha', character: 'Itachi Uchiha', anime: 'Naruto', thumbnailHash: '422fea3b7c0d80ca', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Izabella', character: 'Izabella', anime: 'The Misfit of Demon Academy', thumbnailHash: '4735e0234ea6152d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Izuku Midoriya 1', character: 'Izuku Midoriya', anime: 'My Hero Academia', thumbnailHash: '77effe77a7798b48', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jean (Genshin)', character: 'Jean', anime: 'Genshin Impact', thumbnailHash: '8086c1a58110bc9f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Jean Kirstein', character: 'Jean Kirstein', anime: 'Attack on Titan', thumbnailHash: '70587ea63955121a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jiraiya', character: 'Jiraiya', anime: 'Naruto', thumbnailHash: 'dfc8671719353640', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kaeya', character: 'Kaeya', anime: 'Genshin Impact', thumbnailHash: 'b51906e6e6d4466d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kakashi Hatake', character: 'Kakashi Hatake', anime: 'Naruto', thumbnailHash: '5ce40e643d1567bd', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kakeru Ryuen', character: 'Kakeru Ryuen', anime: 'Classroom of the Elite', thumbnailHash: '78fa9997ff1ffbca', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kamisato Ayaka', character: 'Kamisato Ayaka', anime: 'Genshin Impact', thumbnailHash: '25ddd45b37608f1a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kamisato Ayato', character: 'Kamisato Ayato', anime: 'Genshin Impact', thumbnailHash: '61d735ed79799e6a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Katsuki Bakugo', character: 'Katsuki Bakugo', anime: 'My Hero Academia', thumbnailHash: '07d4f61164512ccf', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kei Karuizawa', character: 'Kei Karuizawa', anime: 'Classroom of the Elite', thumbnailHash: 'c2086fd34995110d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kei Tsukishima', character: 'Kei Tsukishima', anime: 'Haikyu', thumbnailHash: '39c435aac1af3cf0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Ken Sudou', character: 'Ken Sudou', anime: 'Classroom of the Elite', thumbnailHash: 'd3b07d2e2ff41139', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kenma Kozume', character: 'Kenma Kozume', anime: 'Haikyu', thumbnailHash: 'bd9c5d0a4e4bd22c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Keqing', character: 'Keqing', anime: 'Genshin Impact', thumbnailHash: '055be5bc1cd6072d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ketil', character: 'Ketil', anime: 'Vinland Saga', thumbnailHash: 'fe0146aea8a9e2b4', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kikyou Kushida', character: 'Kikyou Kushida', anime: 'Classroom of the Elite', thumbnailHash: '264879be93e23ece', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kishibe', character: 'Kishibe', anime: 'Chainsaw Man', thumbnailHash: 'e840bde396e38f09', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kisuke Urahara', character: 'Kisuke Urahara', anime: 'Bleach', thumbnailHash: '898b8a756cf11cf3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kiyotaka Ayanokoji', character: 'Kiyotaka Ayanokoji', anime: 'Classroom of the Elite', thumbnailHash: 'b683dd309c4b9c0c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Klee', character: 'Klee', anime: 'Genshin Impact', thumbnailHash: 'eb69418f1801c03f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kobeni Higashiyama', character: 'Kobeni Higashiyama', anime: 'Chainsaw Man', thumbnailHash: '0e3bc2170e5270bb', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Koshi Sugawara', character: 'Koshi Sugawara', anime: 'Haikyu', thumbnailHash: '0e5c414359f299e4', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kotaro Bokuto', character: 'Kotaro Bokuto', anime: 'Haikyu', thumbnailHash: '494a1b50336bea55', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kuki Shinobu', character: 'Kuki Shinobu', anime: 'Genshin Impact', thumbnailHash: 'fd527a812779407a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kurama', character: 'Kurama', anime: 'Naruto', thumbnailHash: 'aadbc0733cdf194a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kyojuro Rengoku', character: 'Kyojuro Rengoku', anime: 'Demon Slayer', thumbnailHash: 'ddabf9b257127079', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kyoka Jiro', character: 'Kyoka Jiro', anime: 'My Hero Academia', thumbnailHash: '96175f587b054ac6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Lee Joohee', character: 'Lee Joohee', anime: 'Solo Leveling', thumbnailHash: '5e52df0c817c8c93', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Leif Erikson', character: 'Leif Erikson', anime: 'Vinland Saga', thumbnailHash: 'b8f533143a6a3164', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Levi Ackerman', character: 'Levi Ackerman', anime: 'Attack on Titan', thumbnailHash: 'cd1e9d2a7c7d9719', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Loid Forger', character: 'Loid Forger', anime: 'Spy x Family', thumbnailHash: '7d0ef50e291bbf98', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Loly Aivirrne', character: 'Loly Aivirrne', anime: 'Bleach', thumbnailHash: '8b1867c1f4867018', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Lumine', character: 'Lumine', anime: 'Genshin Impact', thumbnailHash: '92a113b83a4cc01f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Lyney', character: 'Lyney', anime: 'Genshin Impact', thumbnailHash: 'c5988bf7413596e9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Madara Uchiha', character: 'Madara Uchiha', anime: 'Naruto', thumbnailHash: '79d9e1ac563776f9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Maki Zenin', character: 'Maki Zenin', anime: 'Jujutsu Kaisen', thumbnailHash: '01e50a23d679627b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Makima', character: 'Makima', anime: 'Chainsaw Man', thumbnailHash: '3750cb95589e5bcc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Manabu Horikita', character: 'Manabu Horikita', anime: 'Classroom of the Elite', thumbnailHash: 'a0b70f3210fd48a7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Megumi Fushiguro', character: 'Megumi Fushiguro', anime: 'Jujutsu Kaisen', thumbnailHash: '0614233ca054a2ea', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mikasa Ackerman', character: 'Mikasa Ackerman', anime: 'Attack on Titan', thumbnailHash: '1d25f44558127f6d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Miko', character: 'Miko', anime: 'Genshin Impact', thumbnailHash: '775e8df2f81ca6be', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Milim Nava', character: 'Milim Nava', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: '8494c24fb2ea213c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Minato Namikaze', character: 'Minato Namikaze', anime: 'Naruto', thumbnailHash: '6542afcbad336db1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mio Ibuki', character: 'Mio Ibuki', anime: 'Classroom of the Elite', thumbnailHash: '2eb1bae87e6ffefc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mish Necron', character: 'Mish Necron', anime: 'The Misfit of Demon Academy', thumbnailHash: '6720a4b7d988c482', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Miyako Saitou', character: 'Miyako Saitou', anime: 'Oshi no Ko', thumbnailHash: '11a9055c86b9476f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Momo Yaoyorozu', character: 'Momo Yaoyorozu', anime: 'My Hero Academia', thumbnailHash: '4d7e9dfb6ed1c6fa', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mona', character: 'Mona', anime: 'Genshin Impact', thumbnailHash: 'e447e7a69d275131', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Muichiro Tokito', character: 'Muichiro Tokito', anime: 'Demon Slayer', thumbnailHash: '75ce10ff272666ed', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nahida', character: 'Nahida', anime: 'Genshin Impact', thumbnailHash: 'cec4ed8faa88cf8a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Neuvillette', character: 'Neuvillette', anime: 'Genshin Impact', thumbnailHash: '22fca1c763b3203f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nezuko Kamado', character: 'Nezuko Kamado', anime: 'Demon Slayer', thumbnailHash: '039e776600617edc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nilou', character: 'Nilou', anime: 'Genshin Impact', thumbnailHash: '38168089ab294945', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nobara Kugisaki', character: 'Nobara Kugisaki', anime: 'Jujutsu Kaisen', thumbnailHash: '7818f01a2823920d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ochaco Uraraka', character: 'Ochaco Uraraka', anime: 'My Hero Academia', thumbnailHash: 'bf8bbe521e2f480f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Orihime Inoue', character: 'Orihime Inoue', anime: 'Bleach', thumbnailHash: 'c21948525eafab6f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Orochimaru', character: 'Orochimaru', anime: 'Naruto', thumbnailHash: '25929d5bcb3f55d1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Panda', character: 'Panda', anime: 'Jujutsu Kaisen', thumbnailHash: 'c20b7c66e7119781', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Power', character: 'Power', anime: 'Chainsaw Man', thumbnailHash: '77d583668af9cc0f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Prince Rival', character: 'Prince Rival', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f9c0bbfcaba62bcf', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Raiden Shogun', character: 'Raiden Shogun', anime: 'Genshin Impact', thumbnailHash: 'e2af980c6878599f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Reze', character: 'Reze', anime: 'Chainsaw Man', thumbnailHash: 'f0fe1f1653be7bfc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Rokusuke Koenji', character: 'Rokusuke Koenji', anime: 'Classroom of the Elite', thumbnailHash: 'cbbfc4ead7ad986c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rosaria', character: 'Rosaria', anime: 'Genshin Impact', thumbnailHash: 'ffd28703d8896b99', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ryomen Sukuna', character: 'Ryomen Sukuna', anime: 'Jujutsu Kaisen', thumbnailHash: '050ec2994dc49e9b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Sangonomiya Kokomi', character: 'Sangonomiya Kokomi', anime: 'Genshin Impact', thumbnailHash: 'e1ac8e5e1d6b6f40', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sayu', character: 'Sayu', anime: 'Genshin Impact', thumbnailHash: 'd0f29d0e6f6a5e5a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shido Ryuen', character: 'Shido Ryuen', anime: 'Classroom of the Elite', thumbnailHash: 'f2dd3494d75a3b9b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shikamaru Nara', character: 'Shikamaru Nara', anime: 'Naruto', thumbnailHash: '30b0b2b8b60c1c4b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shinobu (Slime)', character: 'Shinobu', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'a7684990a336574b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shishio Tsubaki', character: 'Shishio Tsubaki', anime: 'My Dress Up Darling', thumbnailHash: '2cd6ce0298dee9d3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shoko Ieiri', character: 'Shoko Ieiri', anime: 'Jujutsu Kaisen', thumbnailHash: '0f17ac8e8ac2a1e6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sleeves', character: 'Sleeves', anime: 'Genshin Impact', thumbnailHash: 'e1f2f2a0d2e0a5fa', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Souta Kazama', character: 'Souta Kazama', anime: 'Classroom of the Elite', thumbnailHash: '3ab6e3dd1e4a3f1e', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tanjiro Kamado', character: 'Tanjiro Kamado', anime: 'Demon Slayer', thumbnailHash: '7a9d2c2e2a9e1f4a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Thorfinn', character: 'Thorfinn', anime: 'Vinland Saga', thumbnailHash: '4f2f2e2a1d1a5b1e', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tobio Kageyama', character: 'Tobio Kageyama', anime: 'Haikyu', thumbnailHash: '1e2f3a4b5c6d7e8f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tohru', character: 'Tohru', anime: 'Genshin Impact', thumbnailHash: '2a3b4c5d6e7f8a9b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Todoroki Shoto', character: 'Todoroki Shoto', anime: 'My Hero Academia', thumbnailHash: '3b4c5d6e7f8a9b0c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tohru Adachi', character: 'Tohru Adachi', anime: 'Spy x Family', thumbnailHash: '4c5d6e7f8a9b0c1d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Touka Kirishima', character: 'Touka Kirishima', anime: 'Genshin Impact', thumbnailHash: '5d6e7f8a9b0c1d2e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Tsubaki', character: 'Tsubaki', anime: 'My Dress Up Darling', thumbnailHash: '6e7f8a9b0c1d2e3f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Uryu Ishida', character: 'Uryu Ishida', anime: 'Bleach', thumbnailHash: '7f8a9b0c1d2e3f4a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Venti', character: 'Venti', anime: 'Genshin Impact', thumbnailHash: '8a9b0c1d2e3f4a5b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Vlad King', character: 'Vlad King', anime: 'My Hero Academia', thumbnailHash: '9b0c1d2e3f4a5b6c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Wang Ling', character: 'Wang Ling', anime: 'The Daily Life of the Immortal King', thumbnailHash: '0c1d2e3f4a5b6c7d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Wriothesley', character: 'Wriothesley', anime: 'Genshin Impact', thumbnailHash: '1d2e3f4a5b6c7d8e', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Xiangling', character: 'Xiangling', anime: 'Genshin Impact', thumbnailHash: '2e3f4a5b6c7d8e9f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Xiao', character: 'Xiao', anime: 'Genshin Impact', thumbnailHash: '3f4a5b6c7d8e9f0a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Xingqiu', character: 'Xingqiu', anime: 'Genshin Impact', thumbnailHash: '4a5b6c7d8e9f0a1b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yae Miko', character: 'Yae Miko', anime: 'Genshin Impact', thumbnailHash: '5b6c7d8e9f0a1b2c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yelena', character: 'Yelena', anime: 'Attack on Titan', thumbnailHash: '6c7d8e9f0a1b2c3d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yoimiya', character: 'Yoimiya', anime: 'Genshin Impact', thumbnailHash: '7d8e9f0a1b2c3d4e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yor Forger', character: 'Yor Forger', anime: 'Spy x Family', thumbnailHash: '8e9f0a1b2c3d4e5f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Zenitsu Agatsuma', character: 'Zenitsu Agatsuma', anime: 'Demon Slayer', thumbnailHash: '9f0a1b2c3d4e5f6a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Zhongli', character: 'Zhongli', anime: 'Genshin Impact', thumbnailHash: '0a1b2c3d4e5f6a7b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Grimmjow Jaegerjaquez', character: 'Grimmjow Jaegerjaquez', anime: 'Bleach', thumbnailHash: '1b2c3d4e5f6a7b8c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Moyako Saitou', character: 'Moyako Saitou', anime: 'Oshi no Ko', thumbnailHash: '17e3e5169ba115f6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Daichi Sawamura', character: 'Daichi Sawamura', anime: 'Haikyu', thumbnailHash: '2ad9ca4c62f638fe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Izuku Midoriya 2', character: 'Izuku Midoriya', anime: 'My Hero Academia', thumbnailHash: '23570fa125e72105', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shoyo Hinata', character: 'Shoyo Hinata', anime: 'Haikyu', thumbnailHash: '4e2f3a4b5c6d7e8f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Naruto Uzumaki 2', character: 'Naruto Uzumaki', anime: 'Naruto', thumbnailHash: '6449adc1b938675a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Sasuke Uchiha', character: 'Sasuke Uchiha', anime: 'Naruto', thumbnailHash: '5e4d3c2b1a0f9e8d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Satoru Gojo 2', character: 'Satoru Gojo', anime: 'Jujutsu Kaisen', thumbnailHash: 'd59d31f0a274be2f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Noelle Silva 2', character: 'Noelle Silva', anime: 'Black Clover', thumbnailHash: '9662e1fb56c5ab08', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ichigo Kurosaki 2', character: 'Ichigo Kurosaki', anime: 'Bleach', thumbnailHash: 'a5859dbe2d5dd730', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Luck Voltia 2', character: 'Luck Voltia', anime: 'Black Clover', thumbnailHash: '8ebe2efe62125899', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Sosuke Aizen 2', character: 'Sosuke Aizen', anime: 'Bleach', thumbnailHash: 'b8689d43cf290820', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rukia Kuchiki 2', character: 'Rukia Kuchiki', anime: 'Bleach', thumbnailHash: 'c725aa080bfb2724', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yachiru Kusajishi 2', character: 'Yachiru Kusajishi', anime: 'Bleach', thumbnailHash: '58865a5f162fba6c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yasutora Sado 2', character: 'Yasutora Sado', anime: 'Bleach', thumbnailHash: '4af093e4978ae932', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Byakuya Kuchiki 2', character: 'Byakuya Kuchiki', anime: 'Bleach', thumbnailHash: 'a5afaafc2b2a9652', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yami Sukehiro 2', character: 'Yami Sukehiro', anime: 'Black Clover', thumbnailHash: '281910fa6c26a9c8', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nacht Faust 2', character: 'Nacht Faust', anime: 'Black Clover', thumbnailHash: 'fbdccb28ecd90824', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Julius Novachrono 2', character: 'Julius Novachrono', anime: 'Black Clover', thumbnailHash: 'de7788aa36fdae9b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mereleona 2', character: 'Mereleona', anime: 'Black Clover', thumbnailHash: '6ae80f7b9b5d2959', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nozel Silva 2', character: 'Nozel Silva', anime: 'Black Clover', thumbnailHash: '58fe8d69a2621421', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Vanessa Enoteca 2', character: 'Vanessa Enoteca', anime: 'Black Clover', thumbnailHash: '5c22dd5f2a383100', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Satoru Gojo 3', character: 'Satoru Gojo', anime: 'Jujutsu Kaisen', thumbnailHash: 'd59d31f0a274be2f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yuji Itadori 2', character: 'Yuji Itadori', anime: 'Jujutsu Kaisen', thumbnailHash: '289c69c8b2c243e3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mitsuri Kanroji 2', character: 'Mitsuri Kanroji', anime: 'Demon Slayer', thumbnailHash: 'c74efcafb5a1c873', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shinobu Kocho 2', character: 'Shinobu Kocho', anime: 'Demon Slayer', thumbnailHash: 'a7684990a336574b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Obito Uchiha 2', character: 'Obito Uchiha', anime: 'Naruto', thumbnailHash: '89397be8600cf38d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Benimaru 2', character: 'Benimaru', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'ae5f0e293fff2bfc', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rimuru 2', character: 'Rimuru', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'f56eb2e3f12c334b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rimuru Tempest 2', character: 'Rimuru Tempest', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'dde3977604881403', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shion 2', character: 'Shion', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: '566a22da8f29a222', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shuna 2', character: 'Shuna', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'cdb3348116ea4eee', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Souei 2', character: 'Souei', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'e9149d63486a01a7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Elinalise 2', character: 'Elinalise', anime: 'Jobless Reincarnation', thumbnailHash: 'a577b596b3645007', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Alya 2', character: 'Alya', anime: 'Alya Sometimes Hides Her Feelings', thumbnailHash: '74ad6b95452733e0', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Alya 3', character: 'Alya', anime: 'Alya Sometimes Hides Her Feelings', thumbnailHash: '74ad6b95452733e0', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Frieren 2', character: 'Frieren', anime: 'Frieren Beyond Journey\'s End', thumbnailHash: '6703825bef7d7693', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Rias Gremory 2', character: 'Rias Gremory', anime: 'High School DxD', thumbnailHash: 'cf572ce03e26830a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Albedo 2', character: 'Albedo', anime: 'Overlord', thumbnailHash: '84e8d288dccb7081', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Marin Kitagawa 2', character: 'Marin Kitagawa', anime: 'My Dress Up Darling', thumbnailHash: '2cd6ce0298dee9d3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Finral Roulacase 2', character: 'Finral Roulacase', anime: 'Black Clover', thumbnailHash: 'd2810588085c7aaa', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Miyako Saitou 2', character: 'Miyako Saitou', anime: 'Oshi no Ko', thumbnailHash: '17e3e5169ba115f6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kisuke Urahara 2', character: 'Kisuke Urahara', anime: 'Bleach', thumbnailHash: '898b8a756cf11cf3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nagi Seishiro', character: 'Nagi Seishiro', anime: 'Genshin Impact', thumbnailHash: '9a0b1c2d3e4f5a6b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kazuha', character: 'Kazuha', anime: 'Genshin Impact', thumbnailHash: '0b1c2d3e4f5a6b7c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jean 2', character: 'Jean', anime: 'Genshin Impact', thumbnailHash: '8086c1a58110bc9f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Armin Alert 2', character: 'Armin Alert', anime: 'Attack on Titan', thumbnailHash: '5959226fadf3ca00', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Eren Yeager 2', character: 'Eren Yeager', anime: 'Attack on Titan', thumbnailHash: 'd1683ebe1303a20a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tohru 2', character: 'Tohru', anime: 'Genshin Impact', thumbnailHash: '2a3b4c5d6e7f8a9b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Touka Kirishima 2', character: 'Touka Kirishima', anime: 'Genshin Impact', thumbnailHash: '5d6e7f8a9b0c1d2e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sleeves 2', character: 'Sleeves', anime: 'Genshin Impact', thumbnailHash: 'e1f2f2a0d2e0a5fa', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sayu 2', character: 'Sayu', anime: 'Genshin Impact', thumbnailHash: 'd0f29d0e6f6a5e5a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Jean 3', character: 'Jean', anime: 'Genshin Impact', thumbnailHash: '8086c1a58110bc9f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Keqing 2', character: 'Keqing', anime: 'Genshin Impact', thumbnailHash: '055be5bc1cd6072d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ayato 2', character: 'Kamisato Ayato', anime: 'Genshin Impact', thumbnailHash: '61d735ed79799e6a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Ayaka 2', character: 'Kamisato Ayaka', anime: 'Genshin Impact', thumbnailHash: '25ddd45b37608f1a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Wriothesley 2', character: 'Wriothesley', anime: 'Genshin Impact', thumbnailHash: '1d2e3f4a5b6c7d8e', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yae Miko 2', character: 'Yae Miko', anime: 'Genshin Impact', thumbnailHash: '5b6c7d8e9f0a1b2c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Yoimiya 2', character: 'Yoimiya', anime: 'Genshin Impact', thumbnailHash: '7d8e9f0a1b2c3d4e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Xiangling 2', character: 'Xiangling', anime: 'Genshin Impact', thumbnailHash: '2e3f4a5b6c7d8e9f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Furina 2', character: 'Furina', anime: 'Genshin Impact', thumbnailHash: '861ee658cd6ae69a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nilou 2', character: 'Nilou', anime: 'Genshin Impact', thumbnailHash: '38168089ab294945', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kokomi 2', character: 'Sangonomiya Kokomi', anime: 'Genshin Impact', thumbnailHash: 'e1ac8e5e1d6b6f40', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Fischl 2', character: 'Fischl', anime: 'Genshin Impact', thumbnailHash: '165eed2b293100b0', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Lumine 2', character: 'Lumine', anime: 'Genshin Impact', thumbnailHash: '92a113b83a4cc01f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mona 2', character: 'Mona', anime: 'Genshin Impact', thumbnailHash: 'e447e7a69d275131', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kuki Shinobu 2', character: 'Kuki Shinobu', anime: 'Genshin Impact', thumbnailHash: 'fd527a812779407a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Rosaria 2', character: ' Rosaria', anime: 'Genshin Impact', thumbnailHash: 'ffd28703d8896b99', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Nahida 2', character: 'Nahida', anime: 'Genshin Impact', thumbnailHash: 'cec4ed8faa88cf8a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Eula 2', character: 'Eula', anime: 'Genshin Impact', thumbnailHash: '176d446f029dd428', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Klee 2', character: 'Klee', anime: 'Genshin Impact', thumbnailHash: 'eb69418f1801c03f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Miko 2', character: 'Miko', anime: 'Genshin Impact', thumbnailHash: '775e8df2f81ca6be', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ganyu 2', character: 'Ganyu', anime: 'Genshin Impact', thumbnailHash: '98cb70fd735fd14f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Neuvillette 2', character: 'Neuvillette', anime: 'Genshin Impact', thumbnailHash: '22fca1c763b3203f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Zhongli 2', character: 'Zhongli', anime: 'Genshin Impact', thumbnailHash: '0a1b2c3d4e5f6a7b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Xiao 2', character: 'Xiao', anime: 'Genshin Impact', thumbnailHash: '3f4a5b6c7d8e9f0a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Venti 2', character: 'Venti', anime: 'Genshin Impact', thumbnailHash: '8a9b0c1d2e3f4a5b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Arataki Itto 2', character: 'Arataki Itto', anime: 'Genshin Impact', thumbnailHash: '32d23bf945818800', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Cyno 2', character: 'Cyno', anime: 'Genshin Impact', thumbnailHash: '53c3b1e9d572e394', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kaeya 2', character: 'Kaeya', anime: 'Genshin Impact', thumbnailHash: 'b51906e6e6d4466d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Bennett 2', character: 'Bennett', anime: 'Genshin Impact', thumbnailHash: '2c95482b305f6f11', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Lyney 2', character: 'Lyney', anime: 'Genshin Impact', thumbnailHash: 'c5988bf7413596e9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hotaru 2', character: 'Hotaru', anime: 'Genshin Impact', thumbnailHash: '260f8532c346f827', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Xingqiu 2', character: 'Xingqiu', anime: 'Genshin Impact', thumbnailHash: '4a5b6c7d8e9f0a1b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kazuha 2', character: 'Kazuha', anime: 'Genshin Impact', thumbnailHash: '0b1c2d3e4f5a6b7c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Raiden Shogun 2', character: 'Raiden Shogun', anime: 'Genshin Impact', thumbnailHash: 'e2af980c6878599f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Eren Yeager 3', character: 'Eren Yeager', anime: 'Attack on Titan', thumbnailHash: 'd1683ebe1303a20a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mikasa Ackerman 2', character: 'Mikasa Ackerman', anime: 'Attack on Titan', thumbnailHash: '1d25f44558127f6d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Levi Ackerman 2', character: 'Levi Ackerman', anime: 'Attack on Titan', thumbnailHash: 'cd1e9d2a7c7d9719', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Historia Reiss 2', character: 'Historia Reiss', anime: 'Attack on Titan', thumbnailHash: '8b01f7e26bc70468', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Erwin Smith 2', character: 'Erwin Smith', anime: 'Attack on Titan', thumbnailHash: '9b320f57492a3432', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hange Zoe 2', character: 'Hange Zoe', anime: 'Attack on Titan', thumbnailHash: 'a87793a4a10ef69e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Sasha Blouse 2', character: 'Sasha Blouse', anime: 'Attack on Titan', thumbnailHash: '873dcc5ee62a5474', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Connie Springer 2', character: 'Connie Springer', anime: 'Attack on Titan', thumbnailHash: 'c8560ffcc3accde0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Annie Leonhart 2', character: 'Annie Leonhart', anime: 'Attack on Titan', thumbnailHash: 'd8195c9d25e02d1b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Reiner Braun 2', character: 'Reiner Braun', anime: 'Attack on Titan', thumbnailHash: '4469031dc42388f5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Bertholdt Hoover 2', character: 'Bertholdt Hoover', anime: 'Attack on Titan', thumbnailHash: 'cb2bf04adcfa6840', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Pieck Finger 2', character: 'Pieck Finger', anime: 'Attack on Titan', thumbnailHash: '42b35b7aee9a202e', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Zeke Yeager 2', character: 'Zeke Yeager', anime: 'Attack on Titan', thumbnailHash: 'd9509edc0f96a1c3', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Gabi Braun 2', character: 'Gabi Braun', anime: 'Attack on Titan', thumbnailHash: '19afd8c301e4bae3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Falco Grice 2', character: 'Falco Grice', anime: 'Attack on Titan', thumbnailHash: '008661fcf8c24681', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jean Kirstein 2', character: 'Jean Kirstein', anime: 'Attack on Titan', thumbnailHash: '70587ea63955121a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kenny Ackerman 2', character: 'Kenny Ackerman', anime: 'Attack on Titan', thumbnailHash: 'c0f887ec2e32ccd0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yelena 2', character: 'Yelena', anime: 'Attack on Titan', thumbnailHash: '6c7d8e9f0a1b2c3d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Satoru Gojo 4', character: 'Satoru Gojo', anime: 'Jujutsu Kaisen', thumbnailHash: '3b03f60db649a61a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Megumi Fushiguro 2', character: 'Megumi Fushiguro', anime: 'Jujutsu Kaisen', thumbnailHash: '0614233ca054a2ea', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nobara Kugisaki 2', character: 'Nobara Kugisaki', anime: 'Jujutsu Kaisen', thumbnailHash: '7818f01a2823920d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ryomen Sukuna 2', character: 'Ryomen Sukuna', anime: 'Jujutsu Kaisen', thumbnailHash: '050ec2994dc49e9b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Maki Zenin 2', character: 'Maki Zenin', anime: 'Jujutsu Kaisen', thumbnailHash: '01e50a23d679627b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Aoi Todo 2', character: 'Aoi Todo', anime: 'Jujutsu Kaisen', thumbnailHash: '15488bc1d5e38d78', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mahito 2', character: 'Mahito', anime: 'Jujutsu Kaisen', thumbnailHash: '8b781bb3ec8b5cbe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Choso 2', character: 'Choso', anime: 'Jujutsu Kaisen', thumbnailHash: 'bd74ddd979f1b647', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jogo 2', character: 'Jogo', anime: 'Jujutsu Kaisen', thumbnailHash: '76b5de96464392cc', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Panda 2', character: 'Panda', anime: 'Jujutsu Kaisen', thumbnailHash: 'c20b7c66e7119781', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shoko Ieiri 2', character: 'Shoko Ieiri', anime: 'Jujutsu Kaisen', thumbnailHash: '0f17ac8e8ac2a1e6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Katsuki Bakugo 2', character: 'Katsuki Bakugo', anime: 'My Hero Academia', thumbnailHash: '07d4f61164512ccf', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Todoroki Shoto 2', character: 'Todoroki Shoto', anime: 'My Hero Academia', thumbnailHash: '3b4c5d6e7f8a9b0c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Ochaco Uraraka 2', character: 'Ochaco Uraraka', anime: 'My Hero Academia', thumbnailHash: 'bf8bbe521e2f480f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'All Might 2', character: 'All Might', anime: 'My Hero Academia', thumbnailHash: 'c3bb4d6879a17f16', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hawks 2', character: 'Hawks', anime: 'My Hero Academia', thumbnailHash: '0271c4f18cf23ee1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Endeavor 2', character: 'Endeavor', anime: 'My Hero Academia', thumbnailHash: '18b974b978c9d1fe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shota Aizawa 2', character: 'Shota Aizawa', anime: 'My Hero Academia', thumbnailHash: '6561cf1f06f7d99c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Denki Kaminari 2', character: 'Denki Kaminari', anime: 'My Hero Academia', thumbnailHash: 'b56f8e45ffe3b909', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Eijiro Kirishima 2', character: 'Eijiro Kirishima', anime: 'My Hero Academia', thumbnailHash: '5ce3d33ad342dbd9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kyoka Jiro 2', character: 'Kyoka Jiro', anime: 'My Hero Academia', thumbnailHash: '96175f587b054ac6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Momo Yaoyorozu 2', character: 'Momo Yaoyorozu', anime: 'My Hero Academia', thumbnailHash: '4d7e9dfb6ed1c6fa', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mina Ashido 2', character: 'Mina Ashido', anime: 'My Hero Academia', thumbnailHash: 'b2064cf3781c61e1', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Fumikage Tokoyami 2', character: 'Fumikage Tokoyami', anime: 'My Hero Academia', thumbnailHash: 'ab96cbbe744fa874', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Himiko Toga 2', character: 'Himiko Toga', anime: 'My Hero Academia', thumbnailHash: '5b8b889d3d51a77f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Tomura Shigaraki 2', character: 'Tomura Shigaraki', anime: 'My Hero Academia', thumbnailHash: 'a23045a34031d875', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Dabi 2', character: 'Dabi', anime: 'My Hero Academia', thumbnailHash: 'd2a245fdc00df17d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Izuku Midoriya 3', character: 'Izuku Midoriya', anime: 'My Hero Academia', thumbnailHash: '77effe77a7798b48', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Vlad King 2', character: 'Vlad King', anime: 'My Hero Academia', thumbnailHash: '9b0c1d2e3f4a5b6c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Izuku Midoriya 4', character: 'Izuku Midoriya', anime: 'My Hero Academia', thumbnailHash: '23570fa125e72105', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Gaara 2', character: 'Gaara', anime: 'Naruto', thumbnailHash: 'e073d5be94f06e01', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kakashi Hatake 2', character: 'Kakashi Hatake', anime: 'Naruto', thumbnailHash: '5ce40e643d1567bd', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Jiraiya 2', character: 'Jiraiya', anime: 'Naruto', thumbnailHash: 'dfc8671719353640', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Orochimaru 2', character: 'Orochimaru', anime: 'Naruto', thumbnailHash: '25929d5bcb3f55d1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Minato Namikaze 2', character: 'Minato Namikaze', anime: 'Naruto', thumbnailHash: '6542afcbad336db1', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kurama 2', character: 'Kurama', anime: 'Naruto', thumbnailHash: 'aadbc0733cdf194a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Itachi Uchiha 2', character: 'Itachi Uchiha', anime: 'Naruto', thumbnailHash: '422fea3b7c0d80ca', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Madara Uchiha 2', character: 'Madara Uchiha', anime: 'Naruto', thumbnailHash: '79d9e1ac563776f9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Sasuke Uchiha 2', character: 'Sasuke Uchiha', anime: 'Naruto', thumbnailHash: '5e4d3c2b1a0f9e8d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Hinata Hyuga 2', character: 'Hinata Hyuga', anime: 'Naruto', thumbnailHash: 'a455f39365192746', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Shikamaru Nara 2', character: 'Shikamaru Nara', anime: 'Naruto', thumbnailHash: '30b0b2b8b60c1c4b', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Obito Uchiha 3', character: 'Obito Uchiha', anime: 'Naruto', thumbnailHash: '89397be8600cf38d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Naruto Uzumaki 3', character: 'Naruto Uzumaki', anime: 'Naruto', thumbnailHash: '6449adc1b938675a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Nezuko Kamado 2', character: 'Nezuko Kamado', anime: 'Demon Slayer', thumbnailHash: '039e776600617edc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Zenitsu Agatsuma 2', character: 'Zenitsu Agatsuma', anime: 'Demon Slayer', thumbnailHash: '9f0a1b2c3d4e5f6a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Inosuke Hashibira 2', character: 'Inosuke Hashibira', anime: 'Demon Slayer', thumbnailHash: '17d459204f46461d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kyojuro Rengoku 2', character: 'Kyojuro Rengoku', anime: 'Demon Slayer', thumbnailHash: 'ddabf9b257127079', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Giyu Tomioka 2', character: 'Giyu Tomioka', anime: 'Demon Slayer', thumbnailHash: 'be1abe172e95a80c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Muichiro Tokito 2', character: 'Muichiro Tokito', anime: 'Demon Slayer', thumbnailHash: '75ce10ff272666ed', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tanjiro Kamado 2', character: 'Tanjiro Kamado', anime: 'Demon Slayer', thumbnailHash: '7a9d2c2e2a9e1f4a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Benimaru 3', character: 'Benimaru', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: 'ae5f0e293fff2bfc', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Milim Nava 2', character: 'Milim Nava', anime: 'That Time I Got Reincarnated as a Slime', thumbnailHash: '8494c24fb2ea213c', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Thorfinn 2', character: 'Thorfinn', anime: 'Vinland Saga', thumbnailHash: '4f2f2e2a1d1a5b1e', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Askeladd 2', character: 'Askeladd', anime: 'Vinland Saga', thumbnailHash: 'd46fdac04c21d3c6', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Canute 2', character: 'Canute', anime: 'Vinland Saga', thumbnailHash: '3cb5a9086d9cb1b5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Ketil 2', character: 'Ketil', anime: 'Vinland Saga', thumbnailHash: 'fe0146aea8a9e2b4', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Bjorn 2', character: 'Bjorn', anime: 'Vinland Saga', thumbnailHash: '56a3db33c953aff7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Leif Erikson 2', character: 'Leif Erikson', anime: 'Vinland Saga', thumbnailHash: 'b8f533143a6a3164', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Einar 2', character: 'Einar', anime: 'Vinland Saga', thumbnailHash: 'da32bc7d2c83229c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Floki 2', character: 'Floki', anime: 'Vinland Saga', thumbnailHash: '3c66f6d69c1cd89d', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Denji 2', character: 'Denji', anime: 'Chainsaw Man', thumbnailHash: 'a5607d36536875f5', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Power 2', character: 'Power', anime: 'Chainsaw Man', thumbnailHash: '77d583668af9cc0f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Makima 2', character: 'Makima', anime: 'Chainsaw Man', thumbnailHash: '3750cb95589e5bcc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Aki Hayakawa 2', character: 'Aki Hayakawa', anime: 'Chainsaw Man', thumbnailHash: '1aed3e5ce407f176', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kobeni Higashiyama 2', character: 'Kobeni Higashiyama', anime: 'Chainsaw Man', thumbnailHash: '0e3bc2170e5270bb', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Himeno 2', character: 'Himeno', anime: 'Chainsaw Man', thumbnailHash: '2e17b56d88a3e320', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Reze 2', character: 'Reze', anime: 'Chainsaw Man', thumbnailHash: 'f0fe1f1653be7bfc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Asa Mitaka 2', character: 'Asa Mitaka', anime: 'Chainsaw Man', thumbnailHash: '43b412ca657ac66a', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kishibe 2', character: 'Kishibe', anime: 'Chainsaw Man', thumbnailHash: 'e840bde396e38f09', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Angel Devil 2', character: 'Angel Devil', anime: 'Chainsaw Man', thumbnailHash: '822415571da68141', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Loid Forger 2', character: 'Loid Forger', anime: 'Spy x Family', thumbnailHash: '7d0ef50e291bbf98', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Yor Forger 2', character: 'Yor Forger', anime: 'Spy x Family', thumbnailHash: '8e9f0a1b2c3d4e5f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Anya Forger 2', character: 'Anya Forger', anime: 'Spy x Family', thumbnailHash: 'f952d6efd6c0f2c9', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Fiona Frost 2', character: 'Fiona Frost', anime: 'Spy x Family', thumbnailHash: 'fb70504ec674c1ee', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Damian Desmond 2', character: 'Damian Desmond', anime: 'Spy x Family', thumbnailHash: '592951eaea923b4c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Becky Blackbell 2', character: 'Becky Blackbell', anime: 'Spy x Family', thumbnailHash: 'e3291d3a0bdce8d6', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Franky Franklin 2', character: 'Franky Franklin', anime: 'Spy x Family', thumbnailHash: '512534e883e9d246', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kiyotaka Ayanokoji 2', character: 'Kiyotaka Ayanokoji', anime: 'Classroom of the Elite', thumbnailHash: 'b683dd309c4b9c0c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kei Karuizawa 2', character: 'Kei Karuizawa', anime: 'Classroom of the Elite', thumbnailHash: 'c2086fd34995110d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Arisu Sakayanagi 2', character: 'Arisu Sakayanagi', anime: 'Classroom of the Elite', thumbnailHash: 'cf37f7164102ce3b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kikyou Kushida 2', character: 'Kikyou Kushida', anime: 'Classroom of the Elite', thumbnailHash: '264879be93e23ece', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kakeru Ryuen 2', character: 'Kakeru Ryuen', anime: 'Classroom of the Elite', thumbnailHash: '78fa9997ff1ffbca', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Manabu Horikita 2', character: 'Manabu Horikita', anime: 'Classroom of the Elite', thumbnailHash: 'a0b70f3210fd48a7', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Mio Ibuki 2', character: 'Mio Ibuki', anime: 'Classroom of the Elite', thumbnailHash: '2eb1bae87e6ffefc', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Ken Sudou 2', character: 'Ken Sudou', anime: 'Classroom of the Elite', thumbnailHash: 'd3b07d2e2ff41139', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Rokusuke Koenji 2', character: 'Rokusuke Koenji', anime: 'Classroom of the Elite', thumbnailHash: 'cbbfc4ead7ad986c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Airi Sakura 2', character: 'Airi Sakura', anime: 'Classroom of the Elite', thumbnailHash: '4b9a7e511d990286', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Kei Tsukishima 2', character: 'Kei Tsukishima', anime: 'Haikyu', thumbnailHash: '39c435aac1af3cf0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Tobio Kageyama 2', character: 'Tobio Kageyama', anime: 'Haikyu', thumbnailHash: '1e2f3a4b5c6d7e8f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Shoyo Hinata 2', character: 'Shoyo Hinata', anime: 'Haikyu', thumbnailHash: '4e2f3a4b5c6d7e8f', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kenma Kozume 2', character: 'Kenma Kozume', anime: 'Haikyu', thumbnailHash: 'bd9c5d0a4e4bd22c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Kotaro Bokuto 2', character: 'Kotaro Bokuto', anime: 'Haikyu', thumbnailHash: '494a1b50336bea55', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Koshi Sugawara 2', character: 'Koshi Sugawara', anime: 'Haikyu', thumbnailHash: '0e5c414359f299e4', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Daichi Sawamura 2', character: 'Daichi Sawamura', anime: 'Haikyu', thumbnailHash: '2ad9ca4c62f638fe', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Igris 2', character: 'Igris', anime: 'Solo Leveling', thumbnailHash: '7d94fc8e99daa0d0', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Cha Hae In 2', character: 'Cha Hae In', anime: 'Solo Leveling', thumbnailHash: '90dd408fbbc13e2b', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Baek Yoonho 2', character: 'Baek Yoonho', anime: 'Solo Leveling', thumbnailHash: 'bc5fe4a088983909', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Choi Jong In 2', character: 'Choi Jong In', anime: 'Solo Leveling', thumbnailHash: 'd15a027469c64e59', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Lee Joohee 2', character: 'Lee Joohee', anime: 'Solo Leveling', thumbnailHash: '5e52df0c817c8c93', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Beru 2', character: 'Beru', anime: 'Solo Leveling', thumbnailHash: 'dc0627d8a49ea5d8', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Anosh Voldigoad 2', character: 'Anosh Voldigoad', anime: 'The Misfit of Demon Academy', thumbnailHash: 'c19c2ec984262792', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Noble Lady 2', character: 'Noble Lady', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f164eb988b6e94ca', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Erdomaid Dittijohn 2', character: 'Erdomaid Dittijohn', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f8c18e6587bac566', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Holy Knight 2', character: 'Holy Knight', anime: 'The Misfit of Demon Academy', thumbnailHash: '040bba4e92e3cdc3', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Hybrid Student 2', character: 'Hybrid Student', anime: 'The Misfit of Demon Academy', thumbnailHash: '1762c3777a0deae9', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Izabella 2', character: 'Izabella', anime: 'The Misfit of Demon Academy', thumbnailHash: '4735e0234ea6152d', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Mish Necron 2', character: 'Mish Necron', anime: 'The Misfit of Demon Academy', thumbnailHash: '6720a4b7d988c482', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Prince Rival 2', character: 'Prince Rival', anime: 'The Misfit of Demon Academy', thumbnailHash: 'f9c0bbfcaba62bcf', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Wang Ling 2', character: 'Wang Ling', anime: 'The Daily Life of the Immortal King', thumbnailHash: '2917eb2cf8324771', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Classmate 2', character: 'Classmate', anime: 'The Daily Life of the Immortal King', thumbnailHash: 'de1e0aebbdfa8235', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Grimmjow 2', character: 'Grimmjow Jaegerjaquez', anime: 'Bleach', thumbnailHash: '1b2c3d4e5f6a7b8c', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Uryu Ishida 2', character: 'Uryu Ishida', anime: 'Bleach', thumbnailHash: '7f8a9b0c1d2e3f4a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Loly Aivirrne 2', character: 'Loly Aivirrne', anime: 'Bleach', thumbnailHash: '8b1867c1f4867018', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Orihime Inoue 2', character: 'Orihime Inoue', anime: 'Bleach', thumbnailHash: 'c21948525eafab6f', orientation: 'portrait', category: 'Female Characters' },
  { title: 'Genryusai 2', character: 'Genryusai Shingekuni', anime: 'Bleach', thumbnailHash: '2d3f906709e35389', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Asta 2', character: 'Asta', anime: 'Black Clover', thumbnailHash: '89647794db2acd9a', orientation: 'portrait', category: 'Male Characters' },
  { title: 'Finral Roulacase 3', character: 'Finral Roulacase', anime: 'Black Clover', thumbnailHash: 'd2810588085c7aaa', orientation: 'portrait', category: 'Male Characters' },
];

export const MIGRATED_COUNT = ALL_ARTWORKS.length; // Target: 296
