"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function PublicProfile({ params }: { params: { id: string } }) {
  const [data,setData]=useState<any>(null); const [missing,setMissing]=useState(false);
  useEffect(()=>{fetch(`/api/profile/${params.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setMissing(true));},[params.id]);
  if(missing)return <section className="px-6 pt-44 text-center"><h1 className="font-display text-3xl">Private profile</h1><p className="mt-3 text-fog">This AniPins profile is private or unavailable.</p></section>;
  if(!data)return <section className="mx-auto max-w-5xl px-6 pt-32"><div className="skeleton h-96 rounded-3xl"/></section>;
  const p=data.profile; const initial=(p.nickname||p.name||"A")[0].toUpperCase();
  return <section className="mx-auto max-w-5xl px-4 pb-12 pt-28 md:px-8"><div className="overflow-hidden rounded-3xl bg-panel hairline"><div className="h-44 bg-gradient-to-br from-gold/20 via-soft to-ink md:h-64">{p.cover&&<img src={`/api/img/${p.cover}`} alt="" className="h-full w-full object-cover"/>}</div><div className="px-6 pb-8 md:px-10"><div className="-mt-14 grid h-28 w-28 place-items-center overflow-hidden rounded-full border-4 border-panel bg-soft text-4xl text-gold">{p.avatar?<img src={`/api/img/${p.avatar}`} alt="" className="h-full w-full object-cover"/>:initial}</div><h1 className="mt-4 font-display text-3xl font-semibold">{p.nickname||p.name||"Anime fan"}</h1>{p.bio&&<p className="mt-3 max-w-2xl text-fog">{p.bio}</p>}</div></div>{data.collections.length>0&&<><h2 className="mt-10 font-display text-2xl font-semibold">Collections</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">{data.collections.map((c:any)=><div key={c.id} className="overflow-hidden rounded-2xl bg-panel hairline"><div className="aspect-[4/3] bg-soft">{c.cover&&<img src={`/api/img/${c.cover}`} alt="" className="h-full w-full object-cover"/>}</div><div className="p-3"><p className="font-medium">{c.name}</p><p className="text-xs text-fog">{c.count} artwork</p></div></div>)}</div></>}<h2 className="mt-10 font-display text-2xl font-semibold">Liked artwork</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{data.liked.map((a:any)=><Link key={a.id} href={`/a/${a.id}`} className="overflow-hidden rounded-2xl bg-soft hairline"><img src={`/api/img/${a.thumb}`} alt={a.title||a.character_name} className="aspect-[3/4] w-full object-cover"/><p className="truncate p-2 text-xs">{a.character_name}</p></Link>)}</div></section>;
}
