"use client";
import { useCallback, useEffect, useState } from "react";
import { toast } from "@/components/Toaster";

const deviceName=(ua:string)=>/Android/i.test(ua)?"Android device":/iPhone|iPad/i.test(ua)?"Apple device":/Windows/i.test(ua)?"Windows computer":/Macintosh/i.test(ua)?"Mac computer":"Unknown device";
const date=(value:any)=>value?new Date(value).toLocaleString():"Not available";

export default function AdminSecurity(){
  const [data,setData]=useState<any>(null);const [setup,setSetup]=useState<any>(null);const [recovery,setRecovery]=useState<string[]>([]);const [busy,setBusy]=useState(false);
  const load=useCallback(()=>fetch("/api/admin/security",{cache:"no-store"}).then(r=>r.json()).then(setData),[]);useEffect(()=>{load()},[load]);
  const post=async(body:any)=>{setBusy(true);const r=await fetch("/api/admin/security",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await r.json();setBusy(false);if(!r.ok)toast(result.error||"Security action failed","err");return r.ok?result:null};
  const begin=async()=>{const password=prompt("Confirm your AniPins administrator password");if(!password)return;const result=await post({action:"begin",password});if(result)setSetup(result)};
  const confirmSetup=async()=>{const code=(document.getElementById("totp-confirm") as HTMLInputElement)?.value;const result=await post({action:"confirm",code});if(result){setRecovery(result.recoveryCodes);setSetup(null);await load();toast("Two-factor authentication enabled")}};
  const disable=async()=>{const password=prompt("Enter your administrator password");if(!password)return;const code=prompt("Enter the current 6-digit authenticator code");if(!code)return;const result=await post({action:"disable",password,code});if(result){await load();toast("Two-factor authentication disabled")}};
  const regenerate=async()=>{const code=prompt("Enter the current 6-digit authenticator code");if(!code)return;const result=await post({action:"recovery",code});if(result){setRecovery(result.recoveryCodes);toast("New recovery codes created")}};
  const revoke=async(id:string,current:boolean)=>{if(!confirm(current?"Sign out this device now?":"Revoke this session?"))return;const r=await fetch("/api/admin/security",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:id})});const result=await r.json();if(!r.ok){toast(result.error||"Could not revoke session","err");return}if(result.current)location.href="/login";else{toast("Session revoked");load()}};
  if(!data)return <p className="text-fog">Loading security center…</p>;
  return <div className="max-w-4xl space-y-8"><div><p className="text-xs uppercase tracking-[.25em] text-gold">Admin protection</p><h1 className="mt-2 font-display text-3xl font-semibold">Security center</h1><p className="mt-1 text-sm text-fog">Protect administrator access and review sensitive activity.</p></div>
    <section className="rounded-2xl border border-line bg-panel p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl text-paper">Two-factor authentication</h2><p className="mt-1 text-sm text-fog">{data.twoFactorEnabled?"Protected with an authenticator app.":"Require a rotating code after the administrator password."}</p></div><span className={`rounded-full px-3 py-1 text-xs ${data.twoFactorEnabled?"bg-emerald-500/15 text-emerald-300":"bg-amber-500/15 text-amber-200"}`}>{data.twoFactorEnabled?"Enabled":"Action recommended"}</span></div>
      <div className="mt-5 flex gap-3">{data.twoFactorEnabled?<><button className="btn-ghost" onClick={regenerate} disabled={busy}>New recovery codes</button><button className="rounded-full border border-red-500/30 px-5 py-2.5 text-sm text-red-300" onClick={disable} disabled={busy}>Disable 2FA</button></>:<button className="btn-primary" onClick={begin} disabled={busy}>Set up authenticator</button>}</div>
      {setup&&<div className="mt-6 grid gap-6 rounded-2xl bg-soft p-5 sm:grid-cols-[240px_1fr]"><img src={setup.qr} alt="Authenticator QR code" className="h-60 w-60 rounded-xl bg-white"/><div><h3 className="font-medium text-paper">Scan this code</h3><p className="mt-2 text-sm text-fog">Use Google Authenticator, Microsoft Authenticator, Authy or any TOTP app. If scanning fails, enter this setup key:</p><code className="mt-3 block break-all rounded-xl border border-line p-3 text-gold">{setup.secret}</code><label className="label mt-4">Confirm the 6-digit code</label><input id="totp-confirm" className="input font-mono tracking-[.25em]" inputMode="numeric" maxLength={6}/><button className="btn-primary mt-3" onClick={confirmSetup} disabled={busy}>Confirm and enable</button></div></div>}
      {recovery.length>0&&<div className="mt-6 rounded-2xl border border-amber-400/30 bg-amber-400/[.07] p-5"><h3 className="font-medium text-amber-100">Save these one-time recovery codes now</h3><p className="mt-1 text-sm text-fog">Each code works once. They will not be displayed again.</p><div className="mt-4 grid grid-cols-2 gap-2 font-mono text-sm text-paper sm:grid-cols-4">{recovery.map(code=><code key={code}>{code}</code>)}</div><button className="btn-ghost mt-4" onClick={()=>navigator.clipboard.writeText(recovery.join("\n")).then(()=>toast("Recovery codes copied"))}>Copy codes</button></div>}
    </section>
    <section className="rounded-2xl border border-line bg-panel p-6"><h2 className="font-display text-xl text-paper">Active sessions</h2><p className="mt-1 text-sm text-fog">Devices currently signed in to the administrator account.</p><div className="mt-5 space-y-3">{data.sessions.map((s:any)=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-soft p-4"><div><p className="font-medium text-paper">{deviceName(s.user_agent)} {s.current&&<span className="ml-2 text-xs text-emerald-300">This device</span>}</p><p className="mt-1 text-xs text-fog">IP {s.ip_address||"Unknown"} · Signed in {date(s.created_at)}</p></div><button className="rounded-full border border-line px-4 py-2 text-xs text-fog hover:text-paper" onClick={()=>revoke(s.id,s.current)}>Revoke</button></div>)}</div></section>
    <section className="rounded-2xl border border-line bg-panel p-6"><div className="flex justify-between gap-4"><div><h2 className="font-display text-xl text-paper">Login alerts</h2><p className="mt-1 text-sm text-fog">Every completed administrator login is recorded here.</p></div>{data.alerts.some((a:any)=>!a.read_at)&&<button className="text-sm text-gold" onClick={async()=>{await post({action:"read-alerts"});load()}}>Mark read</button>}</div><div className="mt-5 space-y-3">{data.alerts.length?data.alerts.map((a:any)=><div key={a.id} className={`rounded-xl p-4 ${a.read_at?"bg-soft":"border border-gold/30 bg-gold/[.06]"}`}><p className="text-sm font-medium text-paper">{a.message}</p><p className="mt-1 text-xs text-fog">{deviceName(a.user_agent)} · IP {a.ip_address} · {date(a.created_at)}</p></div>):<p className="text-sm text-fog">No login alerts yet.</p>}</div></section>
    <section className="rounded-2xl border border-line bg-panel p-6"><h2 className="font-display text-xl text-paper">Administrator audit history</h2><p className="mt-1 text-sm text-fog">Upload, edit, publish, feature, deletion and security actions.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-fog"><tr><th className="pb-3">Time</th><th className="pb-3">Action</th><th className="pb-3">Target</th><th className="pb-3">Details</th><th className="pb-3">IP</th></tr></thead><tbody>{data.audit.map((a:any)=><tr key={a.id} className="border-t border-line"><td className="py-3 text-fog">{date(a.created_at)}</td><td className="py-3 text-paper">{a.action.replaceAll("_"," ")}</td><td className="py-3 text-fog">{a.target_type} {a.target_id}</td><td className="max-w-xs truncate py-3 text-fog" title={a.detail}>{a.detail||"—"}</td><td className="py-3 text-fog">{a.ip_address||"—"}</td></tr>)}</tbody></table>{!data.audit.length&&<p className="py-5 text-sm text-fog">Security-sensitive admin actions will appear here.</p>}</div></section>
  </div>;
}
