import Link from "next/link";
import PremiumCheckout from "@/components/PremiumCheckout";
import PremiumLibrary from "@/components/PremiumLibrary";

export const metadata = { title: "AniPins Premium", description: "Unlock exclusive anime reference collections, HD downloads and early access with AniPins Premium." };
const benefits = [["01", "Private reference drops", "Subscriber-only character studies and curated sketch references."], ["02", "Full-quality downloads", "Keep original detail for your art practice."], ["03", "First access", "See new collections before public release."]];
function Crown() { return <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m3.5 7.8 4.2 4.1L12 4.5l4.3 7.4 4.2-4.1-2 10H5.5l-2-10Z" strokeLinejoin="round"/><path d="M7.2 20.3h9.6" strokeLinecap="round"/></svg>; }

export default function PremiumPage() { return <main className="mx-auto max-w-6xl overflow-hidden px-5 pb-24 pt-28 md:px-8 md:pt-36">
  <section className="relative isolate overflow-hidden rounded-[2rem] border border-gold/30 bg-[#15130f] px-6 py-10 shadow-[0_35px_100px_rgba(0,0,0,.45)] sm:px-10 md:rounded-[2.5rem] md:px-14 md:py-16">
    <div className="pointer-events-none absolute -right-32 -top-36 h-[34rem] w-[34rem] rounded-full bg-gold/15 blur-[110px]"/><div className="pointer-events-none absolute -bottom-48 left-[35%] h-[28rem] w-[28rem] rounded-full border border-gold/15"/>
    <div className="relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-gold/35 bg-gold/10 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.22em] text-gold"><Crown/> AniPins Members Club</div><h1 className="mt-7 max-w-xl font-display text-4xl font-semibold leading-[.98] tracking-tight text-paper sm:text-6xl">Your private shelf for <span className="text-gold">serious reference.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-fog sm:text-lg">A quieter, more focused AniPins space for artists who want exceptional character studies, full-quality downloads, and first access to every drop.</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-paper"><span>✦ Monthly membership</span><span>✦ Cancel anytime</span><span>✦ Secure Razorpay billing</span></div></div>
      <aside className="relative mx-auto w-full max-w-md"><div className="absolute -inset-7 rounded-[2rem] bg-gold/10 blur-2xl"/><div className="relative overflow-hidden rounded-[1.75rem] border border-gold/45 bg-gradient-to-br from-[#292013] via-[#15130f] to-[#090909] p-6 shadow-2xl"><div className="absolute -right-14 -top-14 h-36 w-36 rounded-full border border-gold/30"/><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.28em] text-gold">Member pass</p><p className="mt-2 font-display text-2xl text-paper">AniPins Premium</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl border border-gold/40 bg-gold/10 text-gold"><Crown/></div></div><div className="mt-11 border-y border-gold/20 py-5"><p className="text-xs uppercase tracking-[.17em] text-fog">Monthly membership</p><p className="mt-1 font-display text-5xl font-semibold tracking-tight text-paper">₹199<span className="ml-1 text-base font-normal text-fog">/ month</span></p></div><div className="mt-6"><PremiumCheckout/></div><p className="mt-4 text-center text-xs leading-5 text-fog">Starts after payment confirmation. Cancel before your next billing cycle.</p></div></aside></div>
  </section>
  <section className="mt-8 grid gap-4 md:grid-cols-3">{benefits.map(([number,title,copy])=><article key={number} className="group rounded-3xl border border-paper/10 bg-panel p-6 transition-colors hover:border-gold/35"><p className="text-xs font-semibold tracking-[.22em] text-gold/80">{number}</p><h2 className="mt-9 font-display text-2xl font-semibold text-paper">{title}</h2><p className="mt-3 text-sm leading-6 text-fog">{copy}</p><div className="mt-6 h-px w-10 bg-gold/60 transition-all group-hover:w-full"/></article>)}</section>
  <PremiumLibrary/>
  <section className="mt-12 grid gap-5 text-sm text-fog md:grid-cols-2"><div className="rounded-2xl border border-paper/10 bg-panel/60 p-6"><h2 className="font-display text-xl text-paper">Cancel & refunds</h2><p className="mt-3 leading-relaxed">You may cancel at any time; access continues through the already-paid billing period. For duplicate or incorrect charges, contact <a className="text-gold underline" href="mailto:anipins01@gmail.com">anipins01@gmail.com</a> within 7 days.</p></div><div className="rounded-2xl border border-paper/10 bg-panel/60 p-6"><h2 className="font-display text-xl text-paper">Before subscribing</h2><p className="mt-3 leading-relaxed">By subscribing, you agree to the <Link className="text-gold underline" href="/terms">Terms</Link> and <Link className="text-gold underline" href="/privacy">Privacy Policy</Link>. Payments are handled by Razorpay.</p></div></section>
</main>; }
