"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { OfflineArtwork } from "@/lib/native";

export default function OfflineLibrary() {
  const [items,setItems]=useState<(OfflineArtwork&{image?:string})[]>([]);
  useEffect(()=>{(async()=>{try{const saved:OfflineArtwork[]=JSON.parse(localStorage.getItem("anipins-offline-library")||"[]");const cache="caches" in window?await caches.open("anipins-artwork-v1"):null;const resolved=await Promise.all(saved.map(async x=>{if(!cache)return x;const r=await cache.match(`/api/img/${x.thumb}`);return {...x,image:r?URL.createObjectURL(await r.blob()):undefined};}));setItems(resolved);}catch{}})();return()=>items.forEach(x=>x.image&&URL.revokeObjectURL(x.image));},[]);
  const clear=async()=>{localStorage.removeItem("anipins-offline-library");if("caches" in window)await caches.delete("anipins-artwork-v1");setItems([]);};
  return <section className="mx-auto max-w-[1400px] px-4 pb-16 pt-28 md:px-8 md:pt-32"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-3xl font-semibold md:text-4xl">Offline library</h1><p className="mt-2 text-sm text-fog">Recently saved and downloaded artwork kept on this device.</p></div><div className="flex gap-2">{typeof window!=="undefined"&&window.AniPinsAndroid?.openDownloads&&<button onClick={()=>window.AniPinsAndroid?.openDownloads?.()} className="btn-primary !py-2.5">Open Android downloads</button>}{items.length>0&&<button onClick={clear} className="btn-ghost !py-2.5">Clear offline copies</button>}</div></div>{!items.length?<div className="mt-8 rounded-3xl bg-panel p-12 text-center hairline"><p className="text-fog">Your offline library is empty.</p><Link href="/explore" className="btn-primary mt-5">Explore artwork</Link></div>:<div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{items.map((a,i)=><Link key={`${a.kind}-${a.id}-${i}`} href={`/a/${a.id}`} className="group overflow-hidden rounded-2xl bg-panel hairline"><div className="aspect-[3/4] bg-soft">{(a.image||navigator.onLine)&&<img src={a.image||`/api/img/${a.thumb}`} alt={a.title||a.character_name} className="h-full w-full object-cover transition-transform group-hover:scale-105"/>}</div><div className="p-3"><p className="truncate text-sm font-medium">{a.character_name}</p><p className="truncate text-xs text-fog">{a.anime_name}</p><span className="mt-2 inline-block text-[10px] uppercase tracking-wider text-gold">{a.kind}</span></div></Link>)}</div>}</section>;
}
