"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { toast } from "@/components/Toaster";

export default function SettingsPage() {
  const [user, setUser] = useState<any>(null), [guest, setGuest] = useState(false);
  const [following, setFollowing] = useState(true), [updates, setUpdates] = useState(true);
  const [current, setCurrent] = useState(""), [next, setNext] = useState(""), [deletePassword, setDeletePassword] = useState("");
  useEffect(() => { fetch("/api/auth/me", { cache: "no-store" }).then(r => r.json()).then(d => { if (!d.user) setGuest(true); else { setUser(d.user); setFollowing(!!d.user.notify_following); setUpdates(!!d.user.notify_updates); } }); }, []);
  const preferences = async () => { const r = await fetch("/api/account", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "preferences", notifyFollowing: following, notifyUpdates: updates }) }); toast(r.ok ? "Notification preferences saved" : "Could not save preferences", r.ok ? undefined : "err"); };
  const password = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/account", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "password", currentPassword: current, newPassword: next }) }); const d = await r.json(); if (r.ok) { setCurrent(""); setNext(""); toast("Password changed; other sessions were signed out"); } else toast(d.error, "err"); };
  const logoutAll = async () => { if (!confirm("Sign out on every device?")) return; await fetch("/api/account", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "logout-all" }) }); location.href = "/"; };
  const remove = async () => { if (!confirm("Permanently delete your AniPins account, collections, saves and likes?")) return; const r = await fetch("/api/account", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: deletePassword }) }); const d = await r.json(); if (!r.ok) toast(d.error, "err"); else location.href = "/"; };
  if (guest) return <section className="mx-auto max-w-md px-6 pt-40 text-center"><h1 className="font-display text-3xl">Settings</h1><p className="mt-3 text-fog">Sign in to manage your account.</p><Link href="/login" className="btn-primary mt-6">Sign in</Link></section>;
  if (!user) return <section className="mx-auto max-w-3xl px-4 pt-32"><div className="skeleton h-96 rounded-3xl" /></section>;
  return <section className="mx-auto max-w-3xl px-4 pb-16 pt-28 md:px-8 md:pt-32"><h1 className="font-display text-3xl font-semibold md:text-4xl">Settings & privacy</h1><p className="mt-2 text-sm text-fog">Control notifications, security and your account.</p><div className="mt-8 space-y-5">
    <div className="rounded-3xl bg-panel p-6 hairline"><h2 className="font-display text-xl font-semibold">Notifications</h2><div className="mt-5 space-y-4">{[["New artwork from following", following, setFollowing],["AniPins app updates", updates, setUpdates]].map(([label,on,setOn]:any)=><label key={label} className="flex cursor-pointer items-center justify-between gap-4"><span className="text-sm">{label}</span><input type="checkbox" checked={on} onChange={e=>setOn(e.target.checked)} className="h-5 w-5 accent-gold" /></label>)}</div><button onClick={preferences} className="btn-primary mt-5 !py-2.5">Save preferences</button></div>
    <form onSubmit={password} className="rounded-3xl bg-panel p-6 hairline"><h2 className="font-display text-xl font-semibold">Password</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><input type="password" required value={current} onChange={e=>setCurrent(e.target.value)} className="input" placeholder="Current password" /><input type="password" required minLength={8} value={next} onChange={e=>setNext(e.target.value)} className="input" placeholder="New password (8+ characters)" /></div><button className="btn-primary mt-4 !py-2.5">Change password</button></form>
    <div className="rounded-3xl bg-panel p-6 hairline"><h2 className="font-display text-xl font-semibold">Devices</h2><p className="mt-2 text-sm text-fog">End every active login, including this device.</p><button onClick={logoutAll} className="btn-ghost mt-4 !py-2.5">Sign out everywhere</button></div>
    <div className="rounded-3xl border border-red-500/25 bg-red-500/5 p-6"><h2 className="font-display text-xl font-semibold">Delete account</h2><p className="mt-2 text-sm text-fog">This permanently removes your profile, follows, collections, saves and likes.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)} className="input" placeholder="Enter password to confirm" /><button onClick={remove} className="btn shrink-0 bg-red-500 px-6 py-3 text-white hover:bg-red-400">Delete account</button></div></div>
  </div></section>;
}
